# Generated by Django 5.2 on 2025-04-12 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPreservacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemInspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=100, unique=True)),
                ('serial_produto', models.CharField(blank=True, max_length=100)),
                ('dimensao', models.CharField(blank=True, help_text='Formato: Altura x Largura x Comprimento', max_length=100)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('patrimonio', models.BooleanField(default=False)),
                ('preservacao', models.BooleanField(default=False)),
                ('descricao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.descricaoproduto')),
                ('produto_recebido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produtorecebido')),
                ('recebimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recebimento')),
                ('tipo_preservacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipopreservacao')),
            ],
        ),
    ]
