# Generated by Django 5.2 on 2025-04-12 14:12

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipopreservacao_iteminspecao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminspecao',
            name='dimensao',
            field=models.CharField(blank=True, help_text='Formato: Altura x Largura x Comprimento (cm)', max_length=100),
        ),
        migrations.CreateModel(
            name='Preservacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_preservacao', models.DateField()),
                ('proxima_preservacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OK', 'Preservação OK'), ('RESTRICAO', 'Preservação com Restrições')], max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preservacoes', to='core.iteminspecao')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoPreservacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=core.models.upload_anexo_preservacao)),
                ('preservacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.preservacao')),
            ],
        ),
    ]
