# Generated by Django 5.2 on 2025-04-12 14:44

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_movimentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='local',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='setor', chained_model_field='setor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.localizacao'),
        ),
    ]
