# Generated by Django 5.2 on 2025-04-12 14:48

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_movimentacao_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='core.iteminspecao')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=core.models.upload_anexo_solicitacao)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.solicitacaouso')),
            ],
        ),
    ]
