# Generated by Django 4.2.20 on 2025-04-12 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_solicitacaouso_anexosolicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexorecebimento',
            name='arquivo',
            field=models.FileField(upload_to='anexos/'),
        ),
        migrations.AlterField(
            model_name='anexorecebimento',
            name='recebimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recebimento'),
        ),
    ]
