# Generated by Django 4.2.20 on 2025-04-14 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_anexorecebimento_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexorecebimento',
            name='recebimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.recebimento'),
        ),
    ]
