# Generated by Django 4.2.20 on 2025-04-18 12:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_anexorecebimento_recebimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexorecebimento',
            name='arquivo',
            field=models.FileField(upload_to=core.models.upload_anexo_recebimento),
        ),
    ]
